name: freqfun
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - climlab
  - pip
  - pip:
    - setuptools
    - git+https://github.com/LinkedEarth/Pyleoclim_util.git
    - pylipd
    - pangaeapy
