name: freqfun
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - pip
  - pip:
    - xarray==2025.12.0
    - climlab==0.9.1
    - pooch==1.8.2
    - pyleoclim==1.3.0
    - pylipd==1.5.3
    - pangaeapy
